 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shop_lists", type: :request do
  # ShopList. As you add validations to ShopList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ShopList.create! valid_attributes
      get shop_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shop_list = ShopList.create! valid_attributes
      get shop_list_url(shop_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shop_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      shop_list = ShopList.create! valid_attributes
      get edit_shop_list_url(shop_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ShopList" do
        expect {
          post shop_lists_url, params: { shop_list: valid_attributes }
        }.to change(ShopList, :count).by(1)
      end

      it "redirects to the created shop_list" do
        post shop_lists_url, params: { shop_list: valid_attributes }
        expect(response).to redirect_to(shop_list_url(ShopList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ShopList" do
        expect {
          post shop_lists_url, params: { shop_list: invalid_attributes }
        }.to change(ShopList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post shop_lists_url, params: { shop_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shop_list" do
        shop_list = ShopList.create! valid_attributes
        patch shop_list_url(shop_list), params: { shop_list: new_attributes }
        shop_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shop_list" do
        shop_list = ShopList.create! valid_attributes
        patch shop_list_url(shop_list), params: { shop_list: new_attributes }
        shop_list.reload
        expect(response).to redirect_to(shop_list_url(shop_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shop_list = ShopList.create! valid_attributes
        patch shop_list_url(shop_list), params: { shop_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shop_list" do
      shop_list = ShopList.create! valid_attributes
      expect {
        delete shop_list_url(shop_list)
      }.to change(ShopList, :count).by(-1)
    end

    it "redirects to the shop_lists list" do
      shop_list = ShopList.create! valid_attributes
      delete shop_list_url(shop_list)
      expect(response).to redirect_to(shop_lists_url)
    end
  end
end
